import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ShieldCheck, Trash2, X } from 'lucide-react'
import { useForm, useWatch } from 'react-hook-form'
import toast from 'react-hot-toast'
import { Link } from 'react-router-dom'
import apiClient from '../../api/client'
import { EmptyState, ErrorState, LoadingState } from '../common/QueryState'

const inputClass = 'h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-[#111111]'

export default function DocumentPermissionEditor({ document, onClose }) {
  const queryClient = useQueryClient()
  const { register, handleSubmit, reset, control } = useForm({ defaultValues: { user_id: '', can_view: true, can_download: true } })
  const canView = useWatch({ control, name: 'can_view' })
  const permissionsQuery = useQuery({ queryKey: ['document-permissions', document.id], queryFn: () => apiClient.get(`/documents/${document.id}/permissions`).then((response) => response.data.data) })
  const usersQuery = useQuery({ queryKey: ['permission-users'], queryFn: () => apiClient.get('/admin/users', { params: { role: 'client', per_page: 50 } }).then((response) => response.data.data) })
  const save = useMutation({ mutationFn: (values) => apiClient.post(`/documents/${document.id}/permissions`, { ...values, can_view: Boolean(values.can_view), can_download: Boolean(values.can_view && values.can_download) }), onSuccess: () => { toast.success('Permission saved'); reset(); queryClient.invalidateQueries({ queryKey: ['document-permissions', document.id] }) }, onError: (error) => toast.error(error.response?.data?.message || 'Unable to save permission') })
  const remove = useMutation({ mutationFn: (id) => apiClient.delete(`/document-permissions/${id}`), onSuccess: () => { toast.success('Permission removed'); queryClient.invalidateQueries({ queryKey: ['document-permissions', document.id] }) }, onError: () => toast.error('Unable to remove permission') })
  const content = <div className="mx-auto w-full max-w-3xl rounded-2xl border border-slate-200 bg-white p-5 shadow-xl dark:border-zinc-800 dark:bg-[#111111] sm:p-7"><div className="flex items-start justify-between gap-4"><div><span className="inline-flex items-center gap-2 text-xs font-bold uppercase text-blue-600"><ShieldCheck size={16} />Restricted access</span><h2 className="mt-2 !text-xl !font-semibold text-slate-900 dark:text-white">Permissions for {document.title}</h2><p className="mt-2 text-sm text-slate-500">Grant individual clients access to restricted documents.</p></div>{onClose && <button type="button" onClick={onClose} className="icon-button" aria-label="Close permissions"><X size={18} /></button>}</div>
    <form onSubmit={handleSubmit((values) => save.mutate(values))} className="mt-6 grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-zinc-800 dark:bg-zinc-950 md:grid-cols-[1fr_auto_auto_auto] md:items-end"><label className="grid gap-1.5 text-sm font-semibold text-slate-700 dark:text-zinc-200">Client<select {...register('user_id', { required: true })} className={inputClass}><option value="">Select client</option>{(usersQuery.data || []).map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select></label><label className="flex h-11 items-center gap-2 text-sm font-semibold"><input type="checkbox" {...register('can_view')} />View</label><label className="flex h-11 items-center gap-2 text-sm font-semibold"><input type="checkbox" disabled={!canView} {...register('can_download')} />Download</label><button type="submit" disabled={save.isPending} className="button button-primary">{save.isPending ? 'Saving...' : 'Add permission'}</button></form>
    <div className="mt-5">{permissionsQuery.isLoading && <LoadingState label="Loading permissions..." />}{permissionsQuery.isError && <ErrorState message="Unable to load document permissions." onRetry={permissionsQuery.refetch} />}{permissionsQuery.isSuccess && permissionsQuery.data.length === 0 && <EmptyState title="No explicit permissions" description="Add a client to grant access to this restricted document." />}{permissionsQuery.data?.length > 0 && <div className="divide-y divide-slate-200 overflow-hidden rounded-xl border border-slate-200 dark:divide-zinc-800 dark:border-zinc-800">{permissionsQuery.data.map((permission) => <div key={permission.id} className="flex items-center justify-between gap-4 p-4"><div className="min-w-0"><strong className="block truncate text-sm text-slate-900 dark:text-white">{permission.user?.name}</strong><span className="block truncate text-xs text-slate-500">{permission.user?.email} · {permission.can_download ? 'View and download' : 'View only'}</span></div><button type="button" disabled={remove.isPending} onClick={() => remove.mutate(permission.id)} className="icon-button text-red-600" aria-label={`Remove permission for ${permission.user?.name}`}><Trash2 size={16} /></button></div>)}</div>}</div>
    {!onClose && <Link to="/admin/documents" className="button button-secondary mt-6">Back to documents</Link>}</div>

  if (!onClose) return content
  return <div className="dialog-backdrop" role="presentation" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-label={`Permissions for ${document.title}`} className="max-h-[calc(100vh-40px)] w-full overflow-y-auto" onMouseDown={(event) => event.stopPropagation()}>{content}</div></div>
}
